---
# handlers file for git-download-wordpress

- name: restart-apache
  service: 
    name: apache2 
    state: restarted

- name: restart nginx
  service: 
    name: nginx 
    state: restarted
    enabled: yes



